### ISSUE TITLE
Issue tracking for bitbucket addin

### ISSUE THREAD

**Issue by mika76** [aerobatic/aerobatic-io#2]
Hi,

You have so many projects I have no idea where to post this, but there are a couple of bugs I'd like to post for the aerobatic bitbucket addin so please add some way to do this somewhere (maybe link to it from website)

**Comment by Dundonian** [comment]
Hi Mladen, thanks for the note. We're just getting things set up, but you should be able to submit issues here: https://aerobatic.atlassian.net/servicedesk/customer/portal/1

Please let us know if this doesn't work for some reason. Thanks.
